name: Docker Build and Cleanup

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test json        
        run: |
          jq . html/arf.json    

      - name: Sort Bookmarks by name
        run: |
          scripts/sort.py

      - name: Convert Bookmarks
        run: |
          scripts/bookmark_converter.py html/arf.json html/osint-bookmarks.html

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.CI_REGISTRY_USER }}/neo.osint_framework:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.CI_REGISTRY_USER }}/neo.osint_framework:latest
